$exceptions = @{ }

<#
A list of entries that MAY be in the language files, without causing the tests to fail.
This is commonly used in modules that generate localized messages straight from C#.
Specify the full key as it is written in the language files, do not prepend the modulename,
as you would have to in C# code.

Example:
$exceptions['LegalSurplus'] = @(
    'Exception.Streams.FailedCreate'
    'Exception.Streams.FailedDispose'
)
#>
$exceptions['LegalSurplus'] = @(
	# Module uses $script:strings.'Key' pattern which Export-PSMDString cannot detect
	'AI.AnalysisBatch'
	'AI.AnalysisUserMessage'
	'AI.BatchGenerated'
	'AI.BatchGenerating'
	'AI.BatchNotArray'
	'AI.BatchParseFailed'
	'AI.BatchUserMessage'
	'AI.IndustryAnalysisContext'
	'AI.IndustryContext'
	'AI.LocaleMultiple'
	'AI.LocaleSingle'
	'AI.ParseFailed'
	'AI.PlanAdviceApplying'
	'AI.PlanAdviceFailed'
	'AI.PlanAdviceReceived'
	'AI.PlanAdviceRequesting'
	'AI.ProviderConfigured'
	'AI.ProviderNotConfigured'
	'AI.RateLimitWaiting'
	'AI.RequestFailed'
	'AI.RetryAttempt'
	'AI.TestFailed'
	'AI.TestNoResponse'
	'AI.TestStarting'
	'AI.TestSuccess'
	'AI.UnexpectedResponse'
	'AI.UnknownProvider'
	'Audit.WriteFailed'
	'Audit.Written'
	'Connect.Connecting'
	'Connect.Failed'
	'Connect.HealthCheckFailed'
	'Connect.Success'
	'Disconnect.Disconnecting'
	'Disconnect.NoActive'
	'Generation.Complete'
	'Generation.CreatingPlan'
	'Generation.CyclicDependency'
	'Generation.Failed'
	'Generation.MaskingComplete'
	'Generation.MaskingNotSupported'
	'Generation.MaskingStarting'
	'Generation.ParallelStarting'
	'Generation.SkippingComputed'
	'Generation.SkippingSpatial'
	'Generation.SkippedDueToParent'
	'Generation.FKFallbackLoaded'
	'Generation.FKFallbackFailed'
	'Generation.BulkCopyFallback'
	'Generation.RowsSkipped'
	'Generation.Starting'
	'Generation.StreamingStarting'
	'Generation.Table'
	'Generation.TableComplete'
	'Generation.TableOrder'
	'Locale.AICacheHit'
	'Locale.AICategoryFailed'
	'Locale.AICategoryGenerated'
	'Locale.AICategoryGenerating'
	'Locale.AIFailed'
	'Locale.AIFallback'
	'Locale.AIFallbackFailed'
	'Locale.AIGenerated'
	'Locale.AIGenerating'
	'Locale.AIMissingKey'
	'Locale.AIMixGenerating'
	'Locale.AINotConfigured'
	'Locale.AIParseFailed'
	'Locale.Fallback'
	'Locale.MissingKey'
	'Locale.NotFound'
	'Locale.Register'
	'Locale.Registered'
	'Profile.Exporting'
	'Profile.Importing'
	'Profile.RuleCount'
	'Provider.MissingFunction'
	'Provider.NotFound'
	'Provider.Register'
	'Scenario.Applying'
	'Scenario.AutoDetected'
	'Scenario.FallbackSynthetic'
	'Scenario.NotFound'
	'Semantic.AIAnalysis'
	'Semantic.AINotConfigured'
	'Semantic.Analyzing'
	'Semantic.PatternMatch'
	'Semantic.PIIDetected'
	'Semantic.ViewOverride'
	'Schema.Discovering'
	'Schema.ForeignKeys'
	'Schema.Found'
	'Schema.NoTables'
	'StructuredData.AIFailed'
	'StructuredData.AIGenerated'
	'StructuredData.AIGenerating'
	'Transform.Complete'
	'Transform.Exported'
	'Transform.NotFound'
	'Transform.Register'
	'Transform.Starting'
	'Validation.Complete'
	'Validation.FKCheck'
	'Validation.FKViolation'
	'Validation.Starting'
	'Validation.UniqueCheck'
	'Validation.UniqueViolation'
)
<#
A list of entries that MAY be used without needing to have text defined.
This is intended for modules (re-)using strings provided by another module
#>
$exceptions['NoTextNeeded'] = @(
	'Validate.FSPath'
	'Validate.FSPath.File'
	'Validate.FSPath.FileOrParent'
	'Validate.FSPath.Folder'
	'Validate.Path'
	'Validate.Path.Container'
	'Validate.Path.Leaf'
	'Validate.TimeSpan.Positive'
	'Validate.Uri.Absolute'
	'Validate.Uri.Absolute.File'
	'Validate.Uri.Absolute.Https'
)

$exceptions