#
# Module manifest for module 'SqlLabDataGenerator'
#
# Generated by: Ondrej Kracmar
#
# Generated on: 09/12/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SqlLabDataGenerator.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '82fb705b-c1c0-4c63-b5f0-aae7e9b5f962'

# Author of this module
Author = 'Ondrej Kracmar'

# Company or vendor of this module
CompanyName = 'i-system'

# Copyright statement for this module
Copyright = 'Copyright (c) 2026 i-system'

# Description of the functionality provided by this module
Description = 'AI-assisted synthetic data generation platform for SQL Server, SQLite, DuckDB and every other PSSqlRepository provider. Discovers database schema, classifies columns semantically (with OpenAI, Azure OpenAI, or Ollama), generates realistic FK-consistent test data with locale support (en-US, cs-CZ, ...), context-dependent JSON/XML generation via cross-column AI dependencies, and transforms output to Entra ID objects and other formats.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'PSFramework'; ModuleVersion = '1.12.346'; }, 
               @{ModuleName = 'PSSqlRepository'; ModuleVersion = '0.5.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'types\SqlLabDataGenerator.Types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'views\SqlLabDataGenerator.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Clear-SldgCache', 'Connect-SldgDatabase', 'Disconnect-SldgDatabase', 
               'Export-SldgGenerationProfile', 'Export-SldgTransformedData', 
               'Get-SldgAIProvider', 'Get-SldgColumnAnalysis', 
               'Get-SldgDatabaseSchema', 'Get-SldgHealth', 'Get-SldgPromptTemplate', 
               'Get-SldgSession', 'Get-SldgTransformer', 
               'Import-SldgGenerationProfile', 'Invoke-SldgDataGeneration', 
               'New-SldgGenerationPlan', 'Register-SldgLocale', 
               'Register-SldgTransformer', 'Remove-SldgPromptTemplate', 
               'Reset-SldgSession', 'Set-SldgAIProvider', 'Set-SldgGenerationRule', 
               'Set-SldgPromptTemplate', 'Test-SldgAIProvider', 
               'Test-SldgGeneratedData'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'SQL','SqlServer','SQLite','DuckDB','PSSqlRepository','TestData','SyntheticData','DataGeneration','LabData','Database','AI','Ollama','OpenAI','DataMasking','DevOps','Testing','EntraID','Locale','i18n','PSEdition_Core','Windows','Linux','MacOS'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/ondrejkracmar/SqlLabDataGenerator/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ondrejkracmar/SqlLabDataGenerator'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/ondrejkracmar/SqlLabDataGenerator/blob/main/changelog.md'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

